### PR TITLE
Split package in Fhi.HelseId.Web and Fhi.HelseId.Api

### LINKED ISSUE #397: Splitte Fhi.HelseId pakken i Web og Api
Nåværende pakke inneholder både Web delen  og koden for API inngående.

Det har hendt flere ganger at devs bruker f.eks. Api elementer mens de jobber med Web delen, men surprise som resultat.
Den siste delen bør skilles ut som egen liten komponent.

Det er noe felles kode mellom disse, som må håndteres, men dette er ikke mer enn at man bare gjør kopi av dette.

### PR DESCRIPTION
**Pull request by martinmine**
This PR splits up the HelseID package in two packages to target use-cases of an API and a web-based ASP.NET application. Some common code between these two packages remains in the Fhi.HelseId package.

List of breaking changes:
### Namespace changes for classes:
- `TokenExtensions`: `Fhi.HelseId.Web.Infrastructure` -> `Fhi.HelseId.ExtensionMethods`
- `AuthHeaderHandlerForApi`: `Fhi.HelseId.Common` -> `Fhi.HelseId.Api`
- `NoContextException`: `Fhi.HelseId.Common` -> `Fhi.HelseId.Exceptions`
- `ConfigureAuthentication`: `Fhi.HelseId.Api` -> `Fhi.HelseId.Web`
- `MissingConfigurationException`: `Fhi.HelseId.Web` -> `Fhi.HelseId.Exceptions`
- `NoAuthorizationHandler`: `Fhi.HelseId.Api.Handlers` -> `Fhi.HelseId.Web.Handlers`
- `IWhitelist`: `Fhi.HelseId.Web.Services` -> `Fhi.HelseId.Common`
- `Whitelist`: `Fhi.HelseId.Web.Services` -> `Fhi.HelseId.Common`

### Namespace changes for moved extension methods:
- `GetWebKonfigurasjon`: `Fhi.HelseId.Common.ConfigurationExtensions` -> `Fhi.HelseId.Web.ExtensionMethods.ConfigurationExtensions`
- `GetApiKonfigurasjon`: `Fhi.HelseId.Common.ConfigurationExtensions` -> `Fhi.HelseId.Api.ExtensionMethods.ConfigurationExtensions`
- `LogMember`: `Fhi.HelseId.Web.ExtensionMethods` -> `Fhi.HelseId.ExtensionMethods`
- `GetDataProtectionConfig`: `Fhi.HelseId.Api.ExtensionMethods` -> `Fhi.HelseId.Web.ExtensionMethods`

Interface changes:
`IWhitelist`: All functions with parameter `ICurrentUser` has been replaced with `string pidPseudonym`, replace for example:
`whitelist.NameOf(currentUser)` with `whitelist.NameOf(currentUser.PidPseudonym)`

Resolves #397

### CODE REVIEW

**Comment by martinmine** [comment]
@OsirisTerje When reviewing this, I would recommend going through commit by commit. The first commit largly reflects the list of breaking API changes, while the other ones are infrastructure and minor changes around that.

**Comment by yne-bv** [comment]
The split looks good.
I would like if all the **null-error-messages** became issues that can be fixed in separete PR's

**Comment by martinmine** [comment]
Some more breaking changes:

`Fhi.HelseId.Common.BaseAddressUtil` - Removed. Replace calls to ´ToUri("str")´ with ´new Uri("str");´

`Fhi.HelseId.Common.ConfigurationExtensions.GetConfig` -> `Fhi.HelseId.ExtensionMethods.ConfigurationExtensions.GetConfig`

Everything under `Fhi.HelseId.Common.*` will now live under `Fhi.HelseId.Configuration.*` 
The old Fhi.HelseId package is now renamed to Fhi.HelseId.Common, everything which is not under the Fhi.HelseId.Web or Fhi.HelseId.Api will now be under Fhi.HelseId.Common.

**Review by OsirisTerje — APPROVED** [review]
lgtm i think

**Pull request merged**
